glances:
  image: vimagick/glances
  volumes:
    - ./data:/etc/glances
    - /var/run/docker.sock:/var/run/docker.sock:ro
  environment:
    - GLANCES_OPT=-w
  ports:
    - '61208:61208'
  net: host
  pid: host
  restart: always